### ISSUE TITLE
Function with arguments

### ISSUE THREAD

**Issue by vasily-kirichenko** [eiriktsarpalis/QuotationCompiler#15]
Is this the only and ideomatic way to compile a function which can be passed arguments?
```fsharp
let a = QuotationCompiler.ToDynamicAssembly <@ fun x -> x + 1 @>

let f = a.Invoke(null, [||]) :?> int -> int
f 2
```
Is it efficient (I'm worried about the `Invoke` a bit)?

**Comment by eiriktsarpalis** [comment]
Yeah, you can use [`ToFunc`](https://github.com/eiriktsarpalis/QuotationCompiler/blob/master/src/QuotationCompiler/QuotationCompiler.fs#L139-L153) or [`Eval`](https://github.com/eiriktsarpalis/QuotationCompiler/blob/master/src/QuotationCompiler/QuotationCompiler.fs#L155-L161).

**Comment by vasily-kirichenko** [comment]
Ah! I thought those functions are for `unit -> 'T` only.
