### ISSUE TITLE
RunTime error getting a value out of an array

### ISSUE THREAD

**Issue by cognociente** [eiriktsarpalis/QuotationCompiler#6]
I have extracted the below from my code as a self-contained failure case. 

Essentially, I have constructed a quotation expression to extract parameters from an array and it seems to be failing in compiling this construct. 

Error from fsi:
> System.Exception: Compilation failed with errors [|unknown (1,1)-(1,81) typecheck error The field, constructor or member 'Get' is not defined;
  unknown (1,1)-(1,81) parse warning p_typar_spec: from error|].

Error from my actual application provided a bit more info so I provide it also below:
> System.Exception was unhandled
Message: An unhandled exception of type 'System.Exception' occurred in FSharp.Core.dll
Additional information: Compilation failed with errors [|unknown (1,1)-(1,81) typecheck warning **This function is for use by compiled F# code and should not be used directly;**
  unknown (1,1)-(1,81) typecheck warning This function is for use by compiled F# code and should not be used directly;
  unknown (1,1)-(1,81) typecheck error The field, constructor or member 'Get' is not defined|].

Test Case
```
#r "C:\\Users\\xxx\\Source\\Repos\\QuotationCompiler\\bin\\QuotationCompiler.dll"

open FSharp.Quotations
open QuotationCompiler

let r = new Var("r", typeof<float[]>)
let re = Expr.Cast<float[]> ( Expr.Var(r) )

let getParameter (index:int) = Expr.Cast<float> ( Expr.Call(re, typeof<float[]>.GetMethod("Get"), [Expr.Value(index)]) )

let expr = Expr.Cast<float[] -> float> ( 
                Expr.Lambda(r, <@ %(getParameter 1) @> ))

let f = QuotationCompiler.QuotationCompiler.Eval (expr) // fails here here

// test application
let arr = [|5.0; 9.0; 7.0 |] 
f arr
```

**Comment by eiriktsarpalis** [comment]
A good guide in such applications is to see how the F# compiler behaves, since this is what is ultimately being targeted. For instance, if I were to write your code directly in F# it would have been
```fsharp
(fun (r : float[]) -> r.Get 1)
```
which compile errors with the same message. So you need to work around what type of quotation you should be using to get this type of behaviour:
```fsharp
<@ fun (r : float[]) -> r.[1] @>
```
which yields the tree
```fsharp
Lambda (r, Call (None, GetArray, [r, Value (1)]))
```
So you need to use `Microsoft.FSharp.Core.LanguagePrimitives+IntrinsicFunctions.GetArray` instead.

**Comment by cognociente** [comment]
Fair'nuff.
Thanks for the pointer to `IntrinsicFunctions`.

I have converted my code to using `GetArray` and it gets through.
