### ISSUE TITLE
Running time for multiple calls of the dynamic assembly

### ISSUE THREAD

**Issue by cognociente** [eiriktsarpalis/QuotationCompiler#8]
I've noticed that my second call to the function created in the dynamic assembly always runs much faster than the first call. I would assume that subsequent calls would behave in line with the second call.

I would assume that this is because the initial compilation was just a JIT compile and the first call then forces a full compilation? Is this correct?

If so, how can we instruct the dynamic assembly to be compiled fully in the first instance?

**Comment by eiriktsarpalis** [comment]
No, this happens for two reasons:
   1. FSCS performs many static initializations so the first compilation always takes significantly more time than subsequent calls.
   2. The QuotationCompiler library performs caching on compiled quotations by default. So if passing a syntactically identical expression tree a second time, no compilation will take place.

**Comment by eiriktsarpalis** [comment]
That said, JIT compilation might be a theoretical factor, but it is highly negligible when compared to the above.

**Comment by cognociente** [comment]
Maybe I didn't explain myself well above as you seem to be commenting on compile times. 

I'm only calling QuotationCompiler once and creating a lambda function for later usage. It is the performance of calling this lambda function that I am asking about.

**Comment by eiriktsarpalis** [comment]
Ok, so I should assume that you are not using `.Eval()` and have made sure that compilation time has not been included when benchmarking the first call. Even in that case, yes, the first call is always slower, but this is true for any method call in the CLR.

**Comment by cognociente** [comment]
Yes, I measure the call to `Eval()` separately - that's the compile time.

Why would a first method call be slower (even in general in .NET)?

**Comment by eiriktsarpalis** [comment]
I would recommend using `.ToFunc()` instead of `.Eval()` if you need to measure performance.

**Comment by cognociente** [comment]
I changed the main compilation to `.Func()` but performance remained the same. Just to put numbers to it:

Compile ~ 10s
First Run of dynamically compiled function ~ 11s
Second Run of dynamically compiled function ~ 6s

The gap between first and second run just seem really large (to me).

**Comment by eiriktsarpalis** [comment]
Like I said, this is a CLR thing, not related to this library or dynamic assemblies. Such performance discrepancies can be measure in any method call.
