### ISSUE TITLE
Usage of optimization flags in the compile step

### ISSUE THREAD

**Issue by cognociente** [eiriktsarpalis/QuotationCompiler#9]
In QuotationCompiler.fs I don't see the usage of any optimization flags - any reason for this?

In particular, I'm interested in a scenario where I generate the fastest runtime experience possible so this is of interest to me.

**Comment by eiriktsarpalis** [comment]
The FSCS AST compiler applies all optimizations by default, just like F# interactive does.

**Comment by eiriktsarpalis** [comment]
https://github.com/fsharp/FSharp.Compiler.Service/blob/5cea4e1f8025082dfcb4e5a375fa48d126701efb/src/fsharp/fsc.fs#L1973

**Comment by cognociente** [comment]
Good to know, thanks.
